version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: sentenium-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sientenium_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
